const app = express();
const session = require("express-session");
const hbs = require("express-hbs");
const passport = require("passport");
const flash = require("express-flash");
const path = require("path");
const redis = require("redis");
const RedisStore = require("connect-redis")(session);
const methodOverride = require("method-override");
const fs = require("fs");
const LocalStrategy = require("passport-local").Strategy;
require("./config/passport");
